name: Static analysis

on:
  pull_request: ~

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          tools: phpstan:1.11, cs2pr

      - name: Download dependencies
        uses: ramsey/composer-install@v2

      - name: PHPStan
        run: phpstan analyze --no-progress --error-format=checkstyle | cs2pr

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          tools: php-cs-fixer:3.63, cs2pr

      - name: Display PHP-CS-Fixer version
        run: sleep 1 && php-cs-fixer --version

      - name: PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run --format=checkstyle | cs2pr

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          tools: vimeo/psalm:5.25

      - name: Download dependencies
        uses: ramsey/composer-install@v2

      - name: Psalm
        run: psalm --no-progress --output-format=github

  composer-normalize:
    name: Composer Normalize
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          tools: composer-normalize

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Normalize
        run: |
          ok=0
          echo ::group::Root
          composer-normalize --dry-run
          echo ::endgroup::
          for COMPONENT in $(find src -maxdepth 4 -type f -name composer.json | sort)
          do
            echo ::group::$COMPONENT
            localExit=0
            composer-normalize $COMPONENT --dry-run || localExit=1
            ok=$(( $localExit || $ok ))
            echo ::endgroup::
            if [ $localExit -ne 0 ]; then
              echo "::error::$COMPONENT failed"
            fi
          done

          exit $ok
